[package]
edition = "2021"
name = "client"
version = "0.1.0"

[dependencies]
solana-program-mtree = {workspace = true, features = ["no-entrypoint"]}

[dev-dependencies]
solana-sdk.workspace = true
tokio = {workspace = true, features = ["full"]}
